### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by NewsInside** [thetmk/cbr#1]
i have an issue with the script:

`ChaturbateRecorder.py", line 3, in <module>
    import time, datetime, os, sys, requests, configparser, re, subprocess
ImportError: No module named 'requests'`

not running and get this error.
Windows 10 1803 - (compiltation 17134.112)

**Comment by thetmk** [comment]
You need to install the required libraries with pip, like shown in the readme
```
python3.5 -m pip install livestreamer bs4 lxml gevent
```
